x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    logging: *default-logging
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/servarr/config/jellyfin:/config
      - /etc/servarr/media:/data/media
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    logging: *default-logging
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/servarr/config/sonarr:/config
      - /etc/servarr/media/tv:/tv
      - /etc/servarr/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    logging: *default-logging
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/servarr/config/radarr:/config
      - /etc/servarr/media/movies:/movies
      - /etc/servarr/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    logging: *default-logging
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/servarr/config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    logging: *default-logging
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/servarr/config/bazarr:/config
      - /etc/servarr/media/tv:/tv
      - /etc/servarr/media/movies:/movies
    ports:
      - "6767:6767"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.5
    container_name: flaresolverr
    logging: *default-logging
    ports:
      - "8191:8191"
    restart: unless-stopped

  tunarr:
    image: chrisbenincasa/tunarr:latest
    container_name: tunarr
    logging: *default-logging
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /etc/servarr/config/tunarr:/config/tunarr
      - /etc/servarr/config/dizquetv:/.dizquetv
    ports:
      - "8000:8000"
    restart: unless-stopped

  rclone-sync:
    image: rclone/rclone:latest
    container_name: rclone-sync
    logging: *default-logging
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /etc/servarr/rclone:/config/rclone
      - /etc/servarr/downloads:/downloads
    entrypoint: /bin/sh
    command: |
      -c "while true; do \
            rclone sync seedhost:www/clsk.raw.seedhost.eu/clsk/downloads /downloads --progress; \
            sleep 30; \
          done"
