services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    # volumes:
    #   - /path/to/config/jellyfin:/config
    #   - /path/to/media:/media
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    # volumes:
    #   - ./config/sonarr.config.xml:/config/config.xml
    #   - /path/to/media/tv:/tv
    #   - /path/to/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    # volumes:
    #   - /path/to/config/radarr:/config
    #   - /path/to/media/movies:/movies
    #   - /path/to/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    # volumes:
    #   - /path/to/config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    # volumes:
    #   - /path/to/config/bazarr:/config
    #   - /path/to/media:/media
    ports:
      - "6767:6767"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.5
    container_name: flaresolverr
    ports:
      - "8191:8191"
    restart: unless-stopped

  tunarr:
    image: chrisbenincasa/tunarr:latest-arm64
    container_name: tunarr
    environment:
      - TZ=America/Los_Angeles
    # volumes:
    #   - /path/to/config/tunarr:/config/tunarr
    #   - /path/to/config/dizquetv:/.dizquetv
    ports:
      - "8000:8000"
    restart: unless-stopped
